# Exercise 18

## Analyze class homeworks

In [20]:
import pandas as pd
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt

data = pd.read_excel('C:/Users/Alexander Vega/Dropbox/MIIA/SEM II/Mineria de Datos/Clase 9/E18.xlsx')
data.head()

,Sexo,T1,T2,T3,T4,T5,T6
0,H,Un científico de datos y un ingeniero de datos...,NaN,Los árboles de decisión es uno de los algoritm...,NaN,"En el documento ""Do We Need Hundreds of Classi...",Boosting builds models from individual so call...
1,H,Aunque los dos perfiles cuentan con habilidade...,Aunque el conceso no es total en el tema de ma...,NaN,En Machine Learing el propósito de los métodos...,El paper publicado en 2014 hace una evaluación...,Gradient Boosting ClassifierGradient Boosting ...
2,H,Python vs Stata. Analizar información es un pr...,En el marco del Machine Learning encontramos c...,Árbol de clasificación Como su nombre lo indic...,Este es un mecanismo que utiliza varios algori...,El paper analiza 179 clasificadores de 17 dife...,Gradient Boosting Classifier busca aprender de...
3,M,Los algoritmos de machine learning buscan pred...,Los algoritmos de machine learning buscan pred...,Los arboles de decisión pertenecen a los algor...,Consideremos el siguiente ejemplo: Una persona...,¿Se necesitan cientos de modelos para resolver...,NaN
4,H,Python vs R para análisis de datos. A pesar de...,Tipos de aprendizaje en Machine Learning. El M...,Tipos de árboles de decisión y aplicaciones. U...,La combinación de modelos o ensemble es un mod...,En el articulo se analizan cerca de 180 clasif...,XGBoosting vs GBoosting. A pesar de que el alg...

In [21]:
data.shape

(42, 7)

In [24]:
data.isnull().sum()

Sexo     0
T1       1
T2      12
T3      12
T4       6
T5       7
T6      13
T       29
dtype: int64

In [27]:
data['T1']= data['T1'].fillna("")
data['T2']= data['T2'].fillna("")
data['T3']= data['T3'].fillna("")
data['T4']= data['T4'].fillna("")
data['T5']= data['T5'].fillna("")
data['T6']= data['T6'].fillna("")

In [28]:
# Creamos una variable que incluya todos los textos
data['T']=data['T1']+data['T2']+data['T3']+data['T4']+data['T5']+data['T6']

In [29]:
data.head()

,Sexo,T1,T2,T3,T4,T5,T6,T
0,H,Un científico de datos y un ingeniero de datos...,,Los árboles de decisión es uno de los algoritm...,,"En el documento ""Do We Need Hundreds of Classi...",Boosting builds models from individual so call...,Un científico de datos y un ingeniero de datos...
1,H,Aunque los dos perfiles cuentan con habilidade...,Aunque el conceso no es total en el tema de ma...,,En Machine Learing el propósito de los métodos...,El paper publicado en 2014 hace una evaluación...,Gradient Boosting ClassifierGradient Boosting ...,Aunque los dos perfiles cuentan con habilidade...
2,H,Python vs Stata. Analizar información es un pr...,En el marco del Machine Learning encontramos c...,Árbol de clasificación Como su nombre lo indic...,Este es un mecanismo que utiliza varios algori...,El paper analiza 179 clasificadores de 17 dife...,Gradient Boosting Classifier busca aprender de...,Python vs Stata. Analizar información es un pr...
3,M,Los algoritmos de machine learning buscan pred...,Los algoritmos de machine learning buscan pred...,Los arboles de decisión pertenecen a los algor...,Consideremos el siguiente ejemplo: Una persona...,¿Se necesitan cientos de modelos para resolver...,,Los algoritmos de machine learning buscan pred...
4,H,Python vs R para análisis de datos. A pesar de...,Tipos de aprendizaje en Machine Learning. El M...,Tipos de árboles de decisión y aplicaciones. U...,La combinación de modelos o ensemble es un mod...,En el articulo se analizan cerca de 180 clasif...,XGBoosting vs GBoosting. A pesar de que el alg...,Python vs R para análisis de datos. A pesar de...

In [30]:
data.dtypes

Sexo    object
T1      object
T2      object
T3      object
T4      object
T5      object
T6      object
T       object
dtype: object

# Exercise 18.1

Analyze the writing patterns of each student

In [32]:
# Queremos saber el número de palabras y espacios que hay en cada texto

data['word_count'] = data['T'].apply(lambda x: len(str(x).split(" ")))
data[['T','word_count']].head()

                                                   T  word_count
0  Un científico de datos y un ingeniero de datos...        1844
1  Aunque los dos perfiles cuentan con habilidade...        1320
2  Python vs Stata. Analizar información es un pr...        1767
3  Los algoritmos de machine learning buscan pred...        1465
4  Python vs R para análisis de datos. A pesar de...        1666

In [33]:
#Queremos saber el número de caracteres de cada texto

data['char_count'] = data['T'].str.len() ## incluye espacios
data[['T','char_count', 'word_count']].head()

                                                   T  char_count  word_count
0  Un científico de datos y un ingeniero de datos...       11574        1844
1  Aunque los dos perfiles cuentan con habilidade...        8513        1320
2  Python vs Stata. Analizar información es un pr...       11102        1767
3  Los algoritmos de machine learning buscan pred...        9586        1465
4  Python vs R para análisis de datos. A pesar de...       10241        1666

In [34]:
#Queremos ahora saber el promedio de letras por palabra para cada texto

def avg_word(sentence):
  words = sentence.split()
  return (sum(len(word) for word in words)/len(words))

data['avg_word'] = data['T'].apply(lambda x: avg_word(x))
data[['T','char_count', 'word_count', 'avg_word']].head()

,T,char_count,word_count,avg_word
0,Un científico de datos y un ingeniero de datos...,11574,1844,5.279978
1,Aunque los dos perfiles cuentan con habilidade...,8513,1320,5.464286
2,Python vs Stata. Analizar información es un pr...,11102,1767,5.283531
3,Los algoritmos de machine learning buscan pred...,9586,1465,5.536885
4,Python vs R para análisis de datos. A pesar de...,10241,1666,5.150751

In [36]:
# Contar stopwords

import nltk
from nltk.corpus import stopwords
#nltk.download('stopwords')
stop = stopwords.words('Spanish')
print(stop) #imprime la stopwords que hay en español

data['stopwords'] = data['T'].apply(lambda x: len([x for x in x.split() if x in stop]))  #cuenta las stopwords
data[['T','char_count', 'word_count', 'avg_word', 'stopwords']].head()

['de', 'la', 'que', 'el', 'en', 'y', 'a', 'los', 'del', 'se', 'las', 'por', 'un', 'para', 'con', 'no', 'una', 'su', 'al', 'lo', 'como', 'más', 'pero', 'sus', 'le', 'ya', 'o', 'este', 'sí', 'porque', 'esta', 'entre', 'cuando', 'muy', 'sin', 'sobre', 'también', 'me', 'hasta', 'hay', 'donde', 'quien', 'desde', 'todo', 'nos', 'durante', 'todos', 'uno', 'les', 'ni', 'contra', 'otros', 'ese', 'eso', 'ante', 'ellos', 'e', 'esto', 'mí', 'antes', 'algunos', 'qué', 'unos', 'yo', 'otro', 'otras', 'otra', 'él', 'tanto', 'esa', 'estos', 'mucho', 'quienes', 'nada', 'muchos', 'cual', 'poco', 'ella', 'estar', 'estas', 'algunas', 'algo', 'nosotros', 'mi', 'mis', 'tú', 'te', 'ti', 'tu', 'tus', 'ellas', 'nosotras', 'vosostros', 'vosostras', 'os', 'mío', 'mía', 'míos', 'mías', 'tuyo', 'tuya', 'tuyos', 'tuyas', 'suyo', 'suya', 'suyos', 'suyas', 'nuestro', 'nuestra', 'nuestros', 'nuestras', 'vuestro', 'vuestra', 'vuestros', 'vuestras', 'esos', 'esas', 'estoy', 'estás', 'está', 'estamos', 'estáis', 'están', 'esté', 'estés', 'estemos', 'estéis', 'estén', 'estaré', 'estarás', 'estará', 'estaremos', 'estaréis', 'estarán', 'estaría', 'estarías', 'estaríamos', 'estaríais', 'estarían', 'estaba', 'estabas', 'estábamos', 'estabais', 'estaban', 'estuve', 'estuviste', 'estuvo', 'estuvimos', 'estuvisteis', 'estuvieron', 'estuviera', 'estuvieras', 'estuviéramos', 'estuvierais', 'estuvieran', 'estuviese', 'estuvieses', 'estuviésemos', 'estuvieseis', 'estuviesen', 'estando', 'estado', 'estada', 'estados', 'estadas', 'estad', 'he', 'has', 'ha', 'hemos', 'habéis', 'han', 'haya', 'hayas', 'hayamos', 'hayáis', 'hayan', 'habré', 'habrás', 'habrá', 'habremos', 'habréis', 'habrán', 'habría', 'habrías', 'habríamos', 'habríais', 'habrían', 'había', 'habías', 'habíamos', 'habíais', 'habían', 'hube', 'hubiste', 'hubo', 'hubimos', 'hubisteis', 'hubieron', 'hubiera', 'hubieras', 'hubiéramos', 'hubierais', 'hubieran', 'hubiese', 'hubieses', 'hubiésemos', 'hubieseis', 'hubiesen', 'habiendo', 'habido', 'habida', 'habidos', 'habidas', 'soy', 'eres', 'es', 'somos', 'sois', 'son', 'sea', 'seas', 'seamos', 'seáis', 'sean', 'seré', 'serás', 'será', 'seremos', 'seréis', 'serán', 'sería', 'serías', 'seríamos', 'seríais', 'serían', 'era', 'eras', 'éramos', 'erais', 'eran', 'fui', 'fuiste', 'fue', 'fuimos', 'fuisteis', 'fueron', 'fuera', 'fueras', 'fuéramos', 'fuerais', 'fueran', 'fuese', 'fueses', 'fuésemos', 'fueseis', 'fuesen', 'sintiendo', 'sentido', 'sentida', 'sentidos', 'sentidas', 'siente', 'sentid', 'tengo', 'tienes', 'tiene', 'tenemos', 'tenéis', 'tienen', 'tenga', 'tengas', 'tengamos', 'tengáis', 'tengan', 'tendré', 'tendrás', 'tendrá', 'tendremos', 'tendréis', 'tendrán', 'tendría', 'tendrías', 'tendríamos', 'tendríais', 'tendrían', 'tenía', 'tenías', 'teníamos', 'teníais', 'tenían', 'tuve', 'tuviste', 'tuvo', 'tuvimos', 'tuvisteis', 'tuvieron', 'tuviera', 'tuvieras', 'tuviéramos', 'tuvierais', 'tuvieran', 'tuviese', 'tuvieses', 'tuviésemos', 'tuvieseis', 'tuviesen', 'teniendo', 'tenido', 'tenida', 'tenidos', 'tenidas', 'tened']

,T,char_count,word_count,avg_word,stopwords
0,Un científico de datos y un ingeniero de datos...,11574,1844,5.279978,629
1,Aunque los dos perfiles cuentan con habilidade...,8513,1320,5.464286,549
2,Python vs Stata. Analizar información es un pr...,11102,1767,5.283531,821
3,Los algoritmos de machine learning buscan pred...,9586,1465,5.536885,618
4,Python vs R para análisis de datos. A pesar de...,10241,1666,5.150751,775

In [37]:
# Cuántas "palabras" están compuestas de solo dígitos

data['numerics'] = data['T'].apply(lambda x: len([x for x in x.split() if x.isdigit()]))
#data[['T','numerics']].head()

# Cuántas palabras están en mayúsculas

data['upper'] = data['T'].apply(lambda x: len([x for x in x.split() if x.isupper()]))
#data[['T','upper']].head()

data[['T','char_count', 'word_count', 'avg_word', 'stopwords', 'numerics', 'upper']].head()

,T,char_count,word_count,avg_word,stopwords,numerics,upper
0,Un científico de datos y un ingeniero de datos...,11574,1844,5.279978,629,13,21
1,Aunque los dos perfiles cuentan con habilidade...,8513,1320,5.464286,549,6,12
2,Python vs Stata. Analizar información es un pr...,11102,1767,5.283531,821,3,9
3,Los algoritmos de machine learning buscan pred...,9586,1465,5.536885,618,1,6
4,Python vs R para análisis de datos. A pesar de...,10241,1666,5.150751,775,2,13

In [38]:
data[['Sexo','T','char_count', 'word_count', 'avg_word', 'stopwords', 'numerics', 'upper']].head()

,Sexo,T,char_count,word_count,avg_word,stopwords,numerics,upper
0,H,Un científico de datos y un ingeniero de datos...,11574,1844,5.279978,629,13,21
1,H,Aunque los dos perfiles cuentan con habilidade...,8513,1320,5.464286,549,6,12
2,H,Python vs Stata. Analizar información es un pr...,11102,1767,5.283531,821,3,9
3,M,Los algoritmos de machine learning buscan pred...,9586,1465,5.536885,618,1,6
4,H,Python vs R para análisis de datos. A pesar de...,10241,1666,5.150751,775,2,13

Así se caracterizó el patrón de escritura de cada estudiante de acuerdo al número de caracteres, palabras, promedio de letras por palabra, stopwords, caracteres compuestos por solo dígitos y número de palabras en mayúscula utilizadas.

In [ ]:
####

# Exercise 18.2

Evaluate the similarities of the homeworks of the students

tip: https://github.com/orsinium/textdistance

In [39]:
#Eliminar stopwords

stop = stopwords.words('Spanish')
data['T'] = data['T'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))

In [40]:
#Eliminar caracteres no alfanuméricos

data['T'] = data['T'].str.replace('[^\w\s]','') 
#Cuando ^ se utiliza en corchetes, como en este caso, permite encontrar cualquier carácter que NO se encuentre dentro del grupo indicado

In [41]:
#Stemming en español

#Stemming es un proceso que elimina sufijos y demás terminaciones de las palabras.
#Así, por ejemplo, al aplicar este proceso a las palabras caminarás o caminando, el resultado es camin 
#A diferencia del proceso lematización, stemming no tiene en cuenta el contexto del texto al momento de modificar una palabra.

import nltk
from nltk.stem.snowball import SnowballStemmer

spanishStemmer=SnowballStemmer("spanish")
#spanishStemmer.stem("caminando")
#>>camin

data['T'] = data['T'].apply(lambda x: " ".join([spanishStemmer.stem(word) for word in x.split()]))

In [42]:
data[['Sexo','T','char_count', 'word_count', 'avg_word', 'stopwords', 'numerics', 'upper']].head()

,Sexo,T,char_count,word_count,avg_word,stopwords,numerics,upper
0,H,un cientif dat ingenier dat ciert habil comun ...,11574,1844,5.279978,629,13,21
1,H,aunqu dos perfil cuent habil comun exist difer...,8513,1320,5.464286,549,6,12
2,H,python vs stat analiz inform proces necesari t...,11102,1767,5.283531,821,3,9
3,M,los algoritm machin learning busc predec resul...,9586,1465,5.536885,618,1,6
4,H,python vs r analisis dat a pes ambos lenguaj b...,10241,1666,5.150751,775,2,13

In [43]:
strs= data['T'].tolist()

# Función de similitud del coseno utilizando término frecuencia (TF)

from collections import Counter
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def vectors(strs):
    text=[t for t in strs]
    vectorizer=CountVectorizer(text)
    vectorizer.fit(text)
    return vectorizer.transform(text).toarray()

def similarity(strs):
    sim=[t for t in vectors(strs)]
    return cosine_similarity (sim)

In [44]:
vectors(strs)
similarity (strs)

array([[1.        , 0.55215659, 0.44271019, ..., 0.54536177, 0.57646348,
        0.49106699],
       [0.55215659, 1.        , 0.57595023, ..., 0.70178287, 0.62872835,
        0.64787431],
       [0.44271019, 0.57595023, 1.        , ..., 0.658051  , 0.63575055,
        0.64236906],
       ...,
       [0.54536177, 0.70178287, 0.658051  , ..., 1.        , 0.63735666,
        0.66211066],
       [0.57646348, 0.62872835, 0.63575055, ..., 0.63735666, 1.        ,
        0.60621327],
       [0.49106699, 0.64787431, 0.64236906, ..., 0.66211066, 0.60621327,
        1.        ]])

In [45]:
import numpy as np
sim2=similarity (strs)
sim3=sim2.tolist()
sim3
df = pd.DataFrame(sim3)
df

#df es el data frame que contiene el valor de la similitud del coseno para cada texto. Este valor se encuentra entre 0 y 1
#Entre más cercano a uno, más similitud hay entre los dos textos.

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,1.000000,0.552157,0.442710,0.516296,0.532128,0.433207,0.557385,0.558775,0.517651,0.583609,...,0.517207,0.633577,0.557857,0.584345,0.468592,0.538675,0.514229,0.545362,0.576463,0.491067
1,0.552157,1.000000,0.575950,0.643806,0.635896,0.483238,0.184957,0.700510,0.674252,0.723083,...,0.616490,0.676197,0.693873,0.704165,0.549542,0.651268,0.262010,0.701783,0.628728,0.647874
2,0.442710,0.575950,1.000000,0.636696,0.634871,0.492884,0.118565,0.622013,0.616780,0.624623,...,0.627039,0.624781,0.663747,0.581801,0.641765,0.656336,0.099787,0.658051,0.635751,0.642369
3,0.516296,0.643806,0.636696,1.000000,0.655760,0.504565,0.157464,0.688261,0.645760,0.668608,...,0.584215,0.652924,0.650461,0.633321,0.682153,0.683175,0.181055,0.712906,0.638240,0.645390
4,0.532128,0.635896,0.634871,0.655760,1.000000,0.547594,0.114920,0.659637,0.630081,0.665368,...,0.616997,0.700531,0.701496,0.608122,0.624316,0.661953,0.117491,0.663153,0.669524,0.622479
5,0.433207,0.483238,0.492884,0.504565,0.547594,1.000000,0.097757,0.494149,0.557696,0.544130,...,0.542835,0.621483,0.606987,0.453939,0.514757,0.587829,0.078970,0.499568,0.553730,0.437934
6,0.557385,0.184957,0.118565,0.157464,0.114920,0.097757,1.000000,0.202033,0.181928,0.170578,...,0.165365,0.156321,0.127727,0.205262,0.136509,0.154907,0.621457,0.164238,0.148125,0.155652
7,0.558775,0.700510,0.622013,0.688261,0.659637,0.494149,0.202033,1.000000,0.662650,0.754465,...,0.628220,0.690478,0.657103,0.729445,0.594477,0.732954,0.296702,0.720233,0.641709,0.676008
8,0.517651,0.674252,0.616780,0.645760,0.630081,0.557696,0.181928,0.662650,1.000000,0.690999,...,0.650792,0.652227,0.666984,0.653989,0.568271,0.664856,0.208094,0.708520,0.654435,0.643753
9,0.583609,0.723083,0.624623,0.668608,0.665368,0.544130,0.170578,0.754465,0.690999,1.000000,...,0.647510,0.719809,0.736115,0.712947,0.606576,0.741146,0.255029,0.730933,0.708860,0.625352
10,0.420707,0.573728,0.622224,0.578627,0.546627,0.419242,0.132752,0.618411,0.564885,0.603387,...,0.603377,0.525218,0.544960,0.558133,0.609821,0.602253,0.147392,0.660863,0.517856,0.599203
11,0.640071,0.607855,0.631586,0.608058,0.591339,0.475012,0.430180,0.713097,0.611443,0.664158,...,0.556233,0.656939,0.684816,0.657561,0.594166,0.704423,0.395970,0.639295,0.595734,0.692645
12,0.508161,0.716921,0.688353,0.674404,0.649390,0.537913,0.147421,0.716126,0.692188,0.710961,...,0.660295,0.687654,0.748670,0.676481,0.620298,0.729543,0.163973,0.733483,0.632502,0.707222
13,0.510664,0.708684,0.614793,0.668857,0.656941,0.493010,0.187856,0.694885,0.637251,0.664035,...,0.611885,0.677944,0.677480,0.636626,0.592551,0.666094,0.199963,0.681484,0.643834,0.641699
14,0.288575,0.429895,0.468742,0.443898,0.443658,0.369982,0.074737,0.386013,0.448522,0.419395,...,0.390779,0.460664,0.495540,0.349495,0.508471,0.439029,0.025368,0.485246,0.464611,0.440128
15,0.560450,0.172677,0.140918,0.170454,0.135055,0.125851,0.860665,0.193058,0.197823,0.157257,...,0.179065,0.185581,0.154575,0.184914,0.152901,0.172034,0.669678,0.163931,0.152227,0.180609
16,0.506567,0.626525,0.640797,0.661119,0.636810,0.488547,0.151593,0.682241,0.637668,0.693402,...,0.572203,0.621295,0.610920,0.660111,0.579945,0.708360,0.207745,0.670614,0.617589,0.577519
17,0.606751,0.748494,0.641353,0.694192,0.725235,0.596901,0.169498,0.756224,0.736111,0.787553,...,0.654033,0.794997,0.738736,0.720251,0.589017,0.767766,0.253003,0.731395,0.721862,0.622145
18,0.518993,0.681472,0.725343,0.690815,0.660312,0.535860,0.143910,0.679633,0.662684,0.727779,...,0.648680,0.718906,0.710992,0.632460,0.675943,0.717335,0.155153,0.743061,0.684501,0.700923
19,0.601962,0.659368,0.594836,0.621915,0.659753,0.534362,0.178836,0.687636,0.576858,0.693444,...,0.611569,0.743666,0.677154,0.642465,0.594767,0.656443,0.263949,0.633029,0.693979,0.606699
20,0.323826,0.599558,0.513773,0.557023,0.447852,0.359089,0.132357,0.562723,0.593639,0.529792,...,0.509723,0.445954,0.555944,0.492816,0.494203,0.536751,0.104141,0.569580,0.458685,0.643165
21,0.572036,0.688588,0.676608,0.762053,0.708085,0.538951,0.166629,0.730917,0.668167,0.742871,...,0.687294,0.684145,0.731791,0.697665,0.744391,0.782282,0.199442,0.751129,0.695213,0.663138
22,0.532304,0.588931,0.511463,0.517537,0.532646,0.431326,0.163735,0.675978,0.534778,0.595859,...,0.550269,0.639134,0.527769,0.632191,0.441916,0.623907,0.273060,0.581950,0.531787,0.538404
23,0.538729,0.700594,0.629472,0.647210,0.618039,0.476394,0.166479,0.722183,0.675113,0.707165,...,0.613759,0.680051,0.671330,0.696064,0.536631,0.656067,0.263759,0.672415,0.637941,0.654690
24,0.523141,0.654225,0.605153,0.658129,0.622286,0.420303,0.160753,0.729688,0.606414,0.672098,...,0.641496,0.616416,0.589510,0.633131,0.546739,0.663575,0.224396,0.688595,0.530908,0.636530
25,0.435398,0.539406,0.715470,0.640219,0.672332,0.507836,0.127254,0.604440,0.617391,0.600309,...,0.609064,0.629844,0.631035,0.545960,0.663035,0.679990,0.100141,0.649833,0.597750,0.668236
26,0.566999,0.684229,0.643186,0.684031,0.694489,0.600868,0.154235,0.735410,0.671292,0.769819,...,0.598496,0.722359,0.743220,0.681048,0.619766,0.741830,0.198910,0.686999,0.727966,0.612794
27,0.493737,0.552540,0.490469,0.550727,0.603397,0.500357,0.105916,0.505923,0.497088,0.563793,...,0.505371,0.631708,0.701713,0.471199,0.609601,0.572132,0.094788,0.560054,0.609503,0.541398
28,0.478349,0.546582,0.574254,0.588871,0.584751,0.394050,0.157866,0.641194,0.524690,0.587669,...,0.544348,0.569279,0.529551,0.586558,0.558349,0.623287,0.215337,0.574542,0.491993,0.554927
29,0.497624,0.650095,0.673552,0.654090,0.694632,0.641120,0.130147,0.604771,0.671337,0.654178,...,0.654970,0.717637,0.713836,0.574140,0.632951,0.661848,0.114662,0.696889,0.651742,0.626848
30,0.562954,0.590914,0.583402,0.603586,0.566520,0.480274,0.166927,0.678833,0.601191,0.673636,...,0.651582,0.708858,0.625705,0.641086,0.577725,0.666925,0.219391,0.643351,0.614523,0.570993
31,0.446411,0.584309,0.693847,0.612807,0.665472,0.536352,0.112251,0.637603,0.631108,0.640589,...,0.640298,0.664735,0.679474,0.539245,0.649302,0.664241,0.088845,0.658877,0.632928,0.604322
32,0.517207,0.616490,0.627039,0.584215,0.616997,0.542835,0.165365,0.628220,0.650792,0.647510,...,1.000000,0.622597,0.636549,0.574824,0.557379,0.641305,0.168940,0.643994,0.575554,0.583646
33,0.633577,0.676197,0.624781,0.652924,0.700531,0.621483,0.156321,0.690478,0.652227,0.719809,...,0.622597,1.000000,0.756522,0.677792,0.630607,0.701502,0.201845,0.690512,0.745112,0.597431
34,0.557857,0.693873,0.663747,0.650461,0.701496,0.606987,0.127727,0.657103,0.666984,0.736115,...,0.636549,0.756522,1.000000,0.673918,0.681848,0.719240,0.135802,0.687688,0.737068,0.679359
35,0.584345,0.704165,0.581801,0.633321,0.608122,0.453939,0.205262,0.729445,0.653989,0.712947,...,0.574824,0.677792,0.673918,1.000000,0.545100,0.685103,0.286163,0.690180,0.623543,0.624983
36,0.468592,0.549542,0.641765,0.682153,0.624316,0.514757,0.136509,0.594477,0.568271,0.606576,...,0.557379,0.630607,0.681848,0.545100,1.000000,0.670038,0.098586,0.644945,0.658569,0.597573
37,0.538675,0.651268,0.656336,0.683175,0.661953,0.587829,0.154907,0.732954,0.664856,0.741146,...,0.641305,0.701502,0.719240,0.685103,0.670038,1.000000,0.166918,0.702851,0.652800,0.647881
38,0.514229,0.262010,0.099787,0.181055,0.117491,0.078970,0.621457,0.296702,0.208094,0.255029,...,0.168940,0.201845,0.135802,0.286163,0.098586,0.166918,1.000000,0.198008,0.189235,0.162426
39,0.545362,0.701783,0.658051,0.712906,0.663153,0.499568,0.164238,0.720233,0.708520,0.730933,...,0.643994,0.690512,0.687688,0.690180,0.644945,0.702851,0.198008,1.000000,0.637357,0.662111
40,0.576463,0.628728,0.635751,0.638240,0.669524,0.553730,0.148125,0.641709,0.654435,0.708860,...,0.575554,0.745112,0.737068,0.623543,0.658569,0.652800,0.189235,0.637357,1.000000,0.606213
41,0.491067,0.647874,0.642369,0.645390,0.622479,0.437934,0.155652,0.676008,0.643753,0.625352,...,0.583646,0.597431,0.679359,0.624983,0.597573,0.647881,0.162426,0.662111,0.606213,1.000000

In [46]:
####

# Exercise 18.3

Create a classifier to predict the sex of each student

In [48]:
data[['Sexo','T','char_count', 'word_count', 'avg_word', 'stopwords', 'numerics', 'upper']].head()

,Sexo,T,char_count,word_count,avg_word,stopwords,numerics,upper
0,H,un cientif dat ingenier dat ciert habil comun ...,11574,1844,5.279978,629,13,21
1,H,aunqu dos perfil cuent habil comun exist difer...,8513,1320,5.464286,549,6,12
2,H,python vs stat analiz inform proces necesari t...,11102,1767,5.283531,821,3,9
3,M,los algoritm machin learning busc predec resul...,9586,1465,5.536885,618,1,6
4,H,python vs r analisis dat a pes ambos lenguaj b...,10241,1666,5.150751,775,2,13

In [49]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier

In [50]:
vectorizer = TfidfVectorizer()

In [51]:
X=data['T']
X=vectorizer.fit_transform(X)
X.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.0380095 ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.03308222, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [52]:
y=data['Sexo'].map({'H':0,'M':1})
y.head()

0    0
1    0
2    0
3    1
4    0
Name: Sexo, dtype: int64

In [57]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)
algorithm = RandomForestClassifier()
algorithm.fit(X_train, y_train)
y_pred_rf=algorithm.predict(X_test)

C:\anaconda\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

In [58]:
X_train

<21x3636 sparse matrix of type '<class 'numpy.float64'>'
	with 8075 stored elements in Compressed Sparse Row format>

In [60]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_pred_rf, y_test)
print('Accuracy score using a Random Forest: ', round((accuracy)*100,5),'%')

Accuracy score using a Random Forest:  80.95238 %

In [ ]:
####